# Generated by Django 4.2 on 2025-08-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sending', models.DateTimeField(help_text='Введите дату и время начала рассылки', verbose_name='Начало рассылки')),
                ('end_sending', models.DateTimeField(help_text='Введите дату и время окончания рассылки', verbose_name='Окончание рассылки')),
                ('status', models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', help_text='Статус рассылки', max_length=9, verbose_name='Статус')),
                ('client', models.ManyToManyField(related_name='client', to='client.client', verbose_name='Получатели')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['status', 'end_sending', 'start_sending'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_attempt', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки рассылки')),
                ('status', models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], default='Не успешно', help_text='Статус попытки рассылки', max_length=10, verbose_name='Статус')),
                ('answer', models.TextField(verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ['status', 'date_attempt'],
            },
        ),
    ]
