# Generated by Django 4.2 on 2025-08-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['status', 'end_sending', 'start_sending'], 'permissions': [('can_all_view_mailing', 'Просмотр всех рассылок'), ('can_delete_mailing', 'Удаление рассылки'), ('can_update_mailing', 'Обновление рассылки'), ('can_create_mailing', 'Добавление рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], help_text='Статус попытки рассылки', max_length=10, verbose_name='Статус'),
        ),
    ]
