# Generated by Django 4.2 on 2025-08-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Введите адрес электронной почты', max_length=100, unique=True, verbose_name='Электронная почта')),
                ('full_name', models.CharField(help_text='Введите Ваше ФИО в именительном падеже', max_length=100, verbose_name='ФИО')),
                ('message', models.TextField(blank=True, help_text='Добавьте комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Получатель',
                'verbose_name_plural': 'Получатели',
                'ordering': ['full_name', 'email'],
            },
        ),
    ]
